package br.com.anteros.persistence.osql.query;

public enum QueryInjectPosition {
	WITH, START, START_OVERRIDE, AFTER_SELECT, AFTER_PROJECTION, BEFORE_FILTERS, AFTER_FILTERS, BEFORE_GROUP_BY, AFTER_GROUP_BY, BEFORE_HAVING, AFTER_HAVING, BEFORE_ORDER, AFTER_ORDER, END
}
